/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  "Authentication Tokens": { [key: string]: any };
  Bills: { [key: string]: any };
  Catalog: { [key: string]: any };
  Charge: { [key: string]: any };
  Credit: { [key: string]: any };
  Customers: { [key: string]: any };
  "Dispute Management": { [key: string]: any };
  Invoices: { [key: string]: any };
  "Scheduled Invoices": { [key: string]: any };
  "Payment Methods": { [key: string]: any };
  "Password Resets": { [key: string]: any };
  Reports: { [key: string]: any };
  Self: { [key: string]: any };
  Teams: { [key: string]: any };
  Transactions: { [key: string]: any };
  Terminals: { [key: string]: any };
  Webhooks: { [key: string]: any };
}
